# Generated by Django 5.0.2 on 2024-02-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.TextField(db_index=True),
        ),
    ]
